### ISSUE TITLE
Tank direction indicator (lower left hud) does not move

### ISSUE THREAD

**Issue by NextTomShark** [RadianSimulations/ghpc-feedback#120]
Tank direction indicator (lower left hud) does not react when moving tank while restocking is toggled on AND beeing in gunsight. When switching to TC view, the indicator is working when changing tank directions

Win10, GHPC20221008

**Comment by JoshBusuito** [comment]
The indicator shows the direction of the turret and hull relative to the current player view.  If the player is in the gunsight view, the turret indicator will always be pointed straight up.  Furthermore, if the restocking is active, the turret is locked for crew safety, so there would not be any hull direction change relative to the turret.  Therefore, the indicator is working as intended.  Switching to TC view makes it react again because you are now able to look around in other directions.  

Please be sure you fully understand the mechanics of the game before making bug reports.
