### ISSUE TITLE
2 Successive crashes on campaign 

### ISSUE THREAD

**Issue by gergIndo** [RadianSimulations/ghpc-feedback#162]
Playing as NATO, M60, froze and crashed to desktop on two successive campaign missions.  Both missions were "raids", involving eliminating truck depots.  

Edition	Windows 10 Home
Version	21H2
OS build	19044.2728
Experience	Windows Feature Experience Pack 120.2212.4190.0

Game Version 20230228.2

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11011114/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11011115/Player.log)

**Comment by Singleton2** [comment]
I found the same problem on EVERY Raid mission in russian campaign mode:
When reaching the depot from the side and starting firing at the supporting vehicles (M113 or M60) the programm freezes and then crashes. For me, this happens nearly every time.

Windows 11 Pro, Build 22621
i7-1200K, RTX 1070 with actual and older driver
Game Version 20230401.1

There seems to be no crash-report in Temp/Radian Simulation LLC/GHPC/Crashes of that particular crash

[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11189101/Player-prev.log)

**Comment by Singleton2** [comment]
Just retryed it, again with a crash. Perhaps some additional information:
This time it was raid bullfrog, attack from the right side of the depot, killed nearly all m113 and the luncher, when the trucks came in sight, the crash happenened, again without a crash report in the Crashes folder.

See attached picture of my attacking route and the player log
![2023-04-10T092842](https://user-images.githubusercontent.com/130352479/230875812-84c8839b-17c5-43f8-b5c0-05dbcd581c24.png)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11189545/Player.log)

Cheat- Show Instant Damage was on.
My Computer has 3 attached screens.

**Comment by gergIndo** [comment]
Played 3 missions, "Obscene Obsession", a "Recon in Force" and  " Defend", both in campaign mode.......Crash to desktop each time.  During Obsene obsession and the Recon in Force mission, crash to desktop happened during mission, in the Defend mission, crashed during "AAR".  

**Desktop (Please complete the following information):**

 - OS: Windows 10 
 - AMD Ryzen 5 3600X 6-Core Processor  3.80 GHz
 - RAM 16.0 GB
 - 
 - Game Version 20230401.2


[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/11242331/Player-prev.log)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/11242332/Player.log)

**Comment by blake-bracerstudios** [comment]
Each of the logs listed do not point out stack trace information. Without associated crash dump files, which are usually the last line of your player.log, these cannot be diagnosed any further. I will note that @Singleton2 seemed to have a set of missing library files as part of their log, so I would recommend verifying Steam files and if all else fails reinstalling the game.

Otherwise, closing this as known issues with optimization, which are problems we address as development time allows for our small team. If problems persist, please open new issues with Player.log and associated crash dump file, if one is generated. Crash dumps are temporary, so try to get it just after a crash happens.
