### ISSUE TITLE
HEAT Round for East German T-72 Spalling Glitch

### ISSUE THREAD

**Issue by ABELK0** [RadianSimulations/ghpc-feedback#170]
HEAT Rounds from Soviet-made East German T-72 penetrates all the way through M1 Abrams and Sideskirts but only spalls on skirts and exit wound. There is no spalling within the vehicle, making a side shot on the Abrams with HEAT useless.

**To Reproduce**

Go to any mission where T-72s can face off against M1 Abrams (not sure which model of Abrams) and fire a side shot at the M1 Abrams center-mass. APFSDS will penetrate and spall throughout the entire path through the Abrams, HEAT round will only spall at first point of contact (The Sideskirt) and then will not spall again until outside of the tank chassis. 

**Expected Behavior**

HEAT round should spall along path of penetration as the jet makes its way through the vehicle.

**Screenshots**

I didn't get a screenshot but will try to add one later.

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version Most recent patch after April Fools

**Additional context**

I love your work and everything you have done for this game, thank you so much.

**Comment by JoshBusuito** [comment]
The HEAT spalling mechanics are heavily dependent on the exact situation encountered, such as the distance from initial detonation, the thickness of the armor, and the residual penetration potential of the jet.  Our formulas for this are sourced from research papers and real-world ballistic testing results.  As a result, a HEAT jet producing little or no spall when penetrating armor is certainly within valid results.  

In order to determine whether something unexpected happened we would need to see AAR screenshots including the full damage text log.  As described, it sounds pretty normal - the skirt tanked the initial detonation, the hull ate the early spalling, and the relatively thin armor surfaces encountered after that failed to produce impressive spall cones until the jet finally lost enough energy for the penetrations to become volatile again.
