### ISSUE TITLE
The game crashes unexpectedly

### ISSUE THREAD

**Issue by Mrljavi** [RadianSimulations/ghpc-feedback#217]
**Describe the bug**

Mission (Map): Longer Road

**Are you playing with mods?**

No

**Desktop (Please complete the following information):**

 - OS: Windows 10 /64
 - Game Version [20231031]

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/13322408/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/13322409/Player-prev.log)

**Comment by blake-bracerstudios** [comment]
Please find your crash dump file and attach here as your log gives no information specific to the crash. The path can be found in your Player.log file by searching for "A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:"

**Comment by asmidelto** [comment]
Since I'm having the same problem with Long Road crashing the game on start, I'll leave my logs and crash dumps here.

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/13518342/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/13518343/Player-prev.log)


Example no. 1
[crash.dmp](https://github.com/RadianSimulations/ghpc-feedback/files/13518353/crash.dmp)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/13518354/Player.log)

Example no. 2
[crash.dmp](https://github.com/RadianSimulations/ghpc-feedback/files/13518360/crash.dmp)
[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/13518362/Player.log)

**Comment by blake-bracerstudios** [comment]
Reviewed these after some time, and noticed an existing issue with Unity's particle system. Will fix when we have more time to investigate.
