### ISSUE TITLE
M1IP underbelly armour bypassed by round

### ISSUE THREAD

**Issue by badatcodingbean** [RadianSimulations/ghpc-feedback#283]
**Describe the bug**

Underbelly of M1IP not having armour, not sure if bug with T-34-85's APHE round or the armour itself. The screenshots show that it penetrates after being "crushed into armour surface".

**Are you playing with mods?**

No

**To Reproduce**

Go to a hill or other elevated platform and shoot at the underside of abrams, particularly at an angle

**Expected Behavior**

At the angle shown in screenshots, it probably should bounce

**Screenshots**

![20240717003841_1](https://github.com/user-attachments/assets/9e619f19-ca7c-4abd-a638-3aaf2dfc9925)
![20240717003843_1](https://github.com/user-attachments/assets/86b46f3a-f0b2-47a3-8e41-0d457811af62)
![20240717003811_1](https://github.com/user-attachments/assets/8cf29fa4-a274-455a-b652-80ea7695233b)

**Player Log**

N/A

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20240710

**Additional context**

Could be related to ricochet armour bug

**Comment by JoshBusuito** [comment]
This is not a bug. The crush mechanic is a way for large bore rounds to defeat thin plates, based on a real-world phenomenon where the oblique plate doesn't have enough thickness to resist the impact, even at shallow angles. Effectively, the ricochet is bypassed because the plate isn't capable of performing it.
