### ISSUE TITLE
BRDM hitbox not registered a hit in exhaust

### ISSUE THREAD

**Issue by MichalZyzak** [RadianSimulations/ghpc-feedback#296]
**Describe the bug**

A shot reported as a miss went through BRDM-2 exhaust

**Are you playing with mods?**

No

**To Reproduce**

1. Try to hit the vehicle as on the screenshot

A hit should be recoded. Event if its not damaging an important component

![image](https://github.com/user-attachments/assets/18ab9b0f-62a3-4f15-9c8f-84550a97109c)

**Player Log**

[Player-prev.log](https://github.com/user-attachments/files/16600401/Player-prev.log)
[Player.log](https://github.com/user-attachments/files/16600403/Player.log)

**Sources**

None

**Desktop (Please complete the following information):**

 - OS: Windows 11
 - Game Version: 20240806

**Additional context**

None

**Comment by JoshBusuito** [comment]
The AAR can only show a vehicle in one position, while it shows the entire lifetime path of the projectile. Therefore, it must choose one moment to use for vehicle poses, which is usually the moment the shot hits something. You only shot the ground, so the vehicle is shown at its position when the shot hit the ground.

However, if the vehicle was moving (which appears plausible), this can create a situation where it has "driven through" the old path of the shot by the time the position is recorded. That makes it seem like the shot passed through it, but in reality it was not there yet at the time the shot passed that location.

In order to rule this out, we would need to see a test case on a known stationary target, like a BRDM in the Showcase range.

**Comment by MichalZyzak** [comment]
Makes sense :-)

**Comment by MichalZyzak** [comment]
This is one of first targets in Abrams Alley. Aren't those stationary?
