### ISSUE TITLE
M1IP gunner optics view jiggles during cruise control

### ISSUE THREAD

**Issue by TeyKey1** [RadianSimulations/ghpc-feedback#42]
**Describe the bug**

The M1IP gunner optics view jiggles when driving the tank across terrain on the slowest cruise control setting. It appears to be more extreme when the tank is driving on slight downward slope and is still present on even terrain. Though, while driving on upward slopes it does not seem to happen.

**To Reproduce**

1. Use M1IP on Mission "Bold Limit"
2. Drive up the hill then use slowest cruise control setting to drive accross the unplanted field with the slight downward slope
3. Switch to gunner optics view 
4. Now you should be able to observe the jiggling

**Expected Behavior**

The gunner optics view should not jiggle in slowest cruise control setting.

**Desktop:**

 - OS: Windows 10 10.0.19043
 - Game Version 20211106 (patreon build)

**Additional context**

Recording of the problem: https://streamable.com/063eel

**Comment by JoshBusuito** [comment]
This is due to a glitch in the cant correction settings in the fire control system, which kicks on cant correction under a certain vehicle speed.  The glitch is that the optic will level itself when cant correction turns on, instead of staying at the original angle and only moving the reticle.  

The cruise control can land right around the threshold speed for cant correction, resulting in a steady cycling of cant correction on and off, producing this wobble.

**Comment by JoshBusuito** [comment]
Fixed in dev branch
